version: '3.8'
services:
  mongodbc:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: 1234
      MONGO_INITDB_DATABASE: top-trumps
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
#  app:
#    build: .
#    ports:
#      - "8080:8080"
#    depends_on:
#      - mongodbc
volumes:
  mongodata: